adding Rust parser
k4black/codebleu pull request #31
Opened 2024-02-19 23:49 UTC by yijunyu

Adapted `DFG_csharp` to `DFG_rust` in order to parse Rust code using the `tree-sitter-rust` parser.

2024-02-20 07:13 UTC, k4black requested changes
Hi! Thank you a lot! Great efforts  
Could you please fix couple of things I mention in the review comment.

Additionally, could you please tests for rust in `tests/test_codebleu.py` file `test_simple_cases_work_for_all_langs` test case to be sure it is working on all devices.

2024-02-20 07:13 UTC, k4black commented on use.py
> +
Could you please delete this file?

2024-02-20 07:13 UTC, k4black commented on codebleu/codebleu.py
> +AVAILABLE_LANGS = ["java", "javascript", "c_sharp", "php", "c", "cpp", "python", "go", "ruby", "rust"]  # keywords available
Could you also add "rust" to
1. README.md
2. evaluate_app/README.md
2. evaluate_app/codebleu.py - description

2024-02-20 07:13 UTC, k4black commented on codebleu/parser/DFG.py
> +def DFG_rust(root_node, index_to_code, states):
Please check pipeline failed, you need to apply `black` formatter (`python -m black .`)
Also pipeline if checking isort/ruff/mypy

2024-02-27 08:14 UTC, yijunyu commented
Could you take a look at the format fixes? Thanks -- Yijun

2024-02-27 08:18 UTC, k4black commented
@yijunyu Thanks for fixes! 
Regarding formatting im happy if it passes the lining pipeline (it does) thanks! 

Could you please fix other issues i mentioned? Add README info about rust, remove extra file, add test case?
Or i can make it myself, please let me know!

2024-02-27 08:56 UTC, yijunyu commented
Please do so. 

I am a bit tied up recently. 

The Readme won't be significantly different to those for existing languages. If you need help I can start with a similar document.

I have a test case which I may add to the report for this, which fine shall I put it ? Or maybe I just paste it here.

2024-03-01 12:01 UTC, merged